name: forumwebapp
description: "Projeto de Forum para Projeto 3"
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.1
  firebase_auth: ^4.18.1
  cloud_firestore: ^4.15.1
  provider:
  timezone: ^0.10.1
  flutter_timezone: ^4.1.0
  flutter_local_notifications: ^19.2.0
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

 